### ISSUE TITLE
Incorrectly formats string for grid template areas

### ISSUE THREAD

**Issue by xxKeefer** [activeguild/css-to-vanilla-extract#36]
Hey, love this tool, just noticed this.

This css:

```css
.container {
  display: grid; 
  grid-auto-columns: 1fr; 
  grid-template-columns: 1fr 1fr 0.2fr 1.8fr; 
  grid-template-rows: 1fr 1fr 1fr 1fr 1fr; 
  gap: 0px 0px; 
  grid-template-areas: 
    "lorem ipsum dolor sit"
    "lorem ipsum dolor sit"
    "lorem ipsum dolor sit"
    "lorem ipsum dolor sit"
    "lorem ipsum dolor sit"; 
}
```

converts too:

```ts
export const container = style({
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 0.2fr 1.8fr',
    gridTemplateRows: '1fr 1fr 1fr 1fr 1fr',
    gridAutoColumns: '1fr',
    gap: '0px 0px',
    gridAutoFlow: 'row',
    gridTemplateAreas:
        'lorem ipsum dolor sit lorem ipsum dolor sit lorem ipsum dolor sit lorem ipsum dolor sit lorem ipsum dolor sit',
});
```

the property `gridTemplateAreas` needs to include double quotes to break them up. should look like this:

```ts
export const container = style({
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 0.2fr 1.8fr',
    gridTemplateRows: '1fr 1fr 1fr 1fr 1fr',
    gridAutoColumns: '1fr',
    gap: '0px 0px',
    gridAutoFlow: 'row',
    gridTemplateAreas:
        '"lorem ipsum dolor sit" "lorem ipsum dolor sit"  "lorem ipsum dolor sit" "lorem ipsum dolor sit" "lorem ipsum dolor sit"',
});
```

I would love to help out with a PR if you could point me in the right direction, i am not very familiar with Rust but have been looking for a reason to learn. <3
